name: Build_NUnitTests1
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
    {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: BuildStep_NUnitTests
        run: echo "Hello"
      - name: Test Step
        run: |
          pwsh -Command ./Test2.ps1
      
