name: Build_Dependency
on:
  workflow_dispatch:
    {}
  workflow_run:
    workflows: Build_NUnitTests1
    types: [completed]
jobs:
  build_child:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Child
        run: echo ${{ dependencies.Build_NUnitTests1.outputs.GITHUB_RUN_NUMBER }}
      
