name: Build_NUnitTests1
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
    {}
env:
  project_code: ${{ env.testParam }}
  testParam: docksys
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2]
    #- name: Test
      #run: echo ${{ testParam }}
    - name: Test2
      run: echo "${{ env.project_code }}" > test.txt
      
