name: Build_NUnitTests1
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
    {}
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo ${GITHUB_RUN_NUMBER}
    - name: Test
      run: echo ${GITHUB_RUN_NUMBER}
      
