name: Build_NUnitTests1
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
    {}
env:
  testParam: docksys
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo ${GITHUB_REF#refs/heads/}
    - name: Set env
      run: echo ${{github.ref#refs/heads/}}
    #- name: Test
      #run: echo ${{ testParam }}
    - name: Test2
      run: echo "${{ env.testParam }}"
      
