name: Build_NUnitTests1
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
    {}
env:
  project_code:
  testParam: docksys
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
    #- name: Test
      #run: echo ${{ testParam }}
    - name: Test2
      run: echo ${{ github.head_ref || github.ref_name }} 
      
