name: DependentParameters
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
    {}
env:
  testParam: docksys
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      id: build
      run: echo echo "::set-output name=buildNumber::123"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      env: 
        BUILD_NUMBER: ${{ needs.build.outputs.buildNumber }}
      run: echo "Deploying build number $BUILD_NUMBER"
      
