name: DependentParameters
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
    {}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      buildNumber: ${{ steps.step1.outputs.buildNumber }}
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      id: step1
      run: echo "buildNumber=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      env: 
        BUILD_NUMBER: ${{needs.build.outputs.buildNumber}}
      run: echo "Deploying build number $BUILD_NUMBER"
      
