name: Deploy Workflow

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Build Number
        uses: actions/download-artifact@v2
        with:
          name: build_number
      - name: Deploy
        env:
          BUILD_NUMBER: $(cat build_number/build_number.txt)
        run: |
          echo "Deploying build number $BUILD_NUMBER"
