name: TestUploadArtifact
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
env:
  testParam: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |-
        touch integrationtests_group1_script.sh
        echo 'files=$(find "../tests/distribution/Release/publish" -name "*.Tests.dll" | tr '\n' ' ')' >> integrationtests_group1_script.sh
        echo 'echo $files' >> integrationtests_group1_script.sh
    - name: Test
      run: |-
        ls
        cat integrationtests_group1_script.sh
