name: TestUploadArtifact
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch:
env:
  testParam: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |-
        mkdir publish
        touch publish/Test1.txt
        touch publish/Test2.txt
        echo "Hello world" > publish/Test1.txt
    - name: Test
      run: echo "Hello world again" > publish/Test2.txt
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: publish/*
