name: TestWindowsRunner
on: workflow_dispatch
jobs:
  Test-job:
    name: Test Job
    runs-on: windows-latest
    steps:
      - name: Test dotnet version
        run: dotnet --list-sdks
      - name: Install dotnet 3.1
        shell: powershell
        run: |-
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]:Tls, [Net.SecurityProtocolType]:Tls11, [Net.SecurityProtocolType]:Tls12, [Net.SecurityProtocolType]:Ss13
          
