name: TestWindowsRunner
on: workflow_dispatch
jobs:
  Test-job:
    name: Test Job
    runs-on: windows-latest
    steps:
      - name: Test dotnet version
        run: dotnet --list-sdks
      - name: Install dotnet 3.1
        shell: powershell
        run: |-
          Function Install-Sdk3.1 {
            param ( [string] $WorkingFolder
          )
            $download = "https://download.visualstudio.microsoft.com/download/pr/b70ad520-0e60-43f5-aee2-d3965094a40d/667c122b3736dcbfa1beff08092dbfc3/dotnet-sdk-3.1.426-win-x64.exe"
            $SDK_installer = Join-Path -Path $WorkingFolder -ChildPath "dotnet-sdk-3.1.426-win-x64.exe"
            Invoke-WebRequest -Uri $download -OutFile $SDK_installer
            If ((Test-Path $SDK_installer)) {
              "File downloaded!"
            }
            else {
              "File not downloaded!"
            }
            "attempting to install..."
            try {
              Start-Process -FilePath "dotnet-sdk-3.1.426-win-x64.exe" -NoNewWindow -Wait -PassThru
            }
            catch {
              $_.Exception
            }
          }
          Install-SDK3.1 "."
      - name: Test dotnet sdks
        run: dotnet --list-sdks
      - name: Test dotnet version
        run: dotnet --version
          
